### ISSUE TITLE
Upgrade to v1.6.1

### ISSUE THREAD

**Issue by tylersatre** [homebridge/docker-homebridge#514]
### Feature Description

Would it be possible to get the image updated so it's using v1.6.1 instead of v1.5.0?  I was digging into the workflow files a bit because I wanted to put up a PR, but it didn't seem as easy as just bumping a version number here 😢

**Comment by NorthernMan54** [comment]
Check your image location, we updated and moved the image to homebridge

**Comment by tylersatre** [comment]
> Check your image location, we updated and moved the image to homebridge

I’m using `homebridge/homebridge:latest`

**Comment by dennypage** [comment]
FWIW, I am using  homebridge/homebridge from Docker Hub (https://hub.docker.com/r/homebridge/homebridge) and I see v1.6.1.

**Comment by tylersatre** [comment]
I tested out a fresh pull on a different computer and it was v1.6.1, I went ahead and did the update through the web UI on my existing container.  I had thought the version of homebridge would be set by the container, but looks like it's just stored in `package.json` that's in the volume mapping to `/homebridge`.
