### ISSUE TITLE
Docker --net=host don't work on Mac OS and windows servers

### ISSUE THREAD

**Issue by rodin-andrei** [homebridge/docker-homebridge#516]
### Current Situation
How run this soft on Mac OS device or device by windows server management
https://docs.docker.com/network/host/

The host networking driver only works on Linux hosts, and is not supported on Docker for Mac, Docker for Windows, or Docker EE for Windows Server.

### Docker Config

```yml
docker run --net=host  -d homebridge/homebridge:latest
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
This is noted in the README

https://github.com/homebridge/docker-homebridge#compatibility

**Comment by rodin-andrei** [comment]
Thx
