### ISSUE TITLE
Update to Node.js v18.0.0

### ISSUE THREAD

**Issue by maorielvis** [homebridge/docker-homebridge#517]
### Current Situation

I need to update Node to Node.js v18.0.0. 

I've pulled down the latest build, and it is still showing Node version v16.13.2

Does the latest build support v18.0.0?

### Docker Config

```yml
.
```

### Host Operating System

QNAP

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
Yes the latest build does support a more recent nodejs. Pleaee double check your image location, as we moved the image to homebridge/homebridge

**Comment by maorielvis** [comment]
Thanks @NorthernMan54 have updated the container with that new image and it worked.

Thanks for your help
